// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// structures
struct BubbleSort
{
  struct BubbleSort_vtable *vptr;
};
struct BBS
{
  struct BBS_vtable *vptr;
  int* number;
  int size;
};
// vtables structures
struct BubbleSort_vtable
{
};

struct BBS_vtable
{
  int (*Start)();
  int (*Sort)();
  int (*Print)();
  int (*Init)();
};


// methods
int BBS_Start(struct BBS * this, int sz)
{
  int aux01;
  struct BBS * x_1;
  struct BBS * x_2;
  struct BBS * x_3;
  struct BBS * x_4;

  aux01 = (x_1=this, x_1->vptr->Init(x_1, this->sz));
  aux01 = (x_2=this, x_2->vptr->Print(x_2));
  System_out_println (99999);
  aux01 = (x_3=this, x_3->vptr->Sort(x_3));
  aux01 = (x_4=this, x_4->vptr->Print(x_4));
  return 0;
}
int BBS_Sort(struct BBS * this)
{
  int nt;
  int i;
  int aux02;
  int aux04;
  int aux05;
  int aux06;
  int aux07;
  int j;
  int t;

  i = this->size - 1;
  aux02 = 0 - 1;
  while(this->aux02 < this->i)
  {
    {
      j = 1;
      while(this->j < this->i+1)
      {
        {
          aux07 = this->j - 1;
          aux04 = this->number[this->aux07];
          aux05 = this->number[this->j];
          if (this->aux05 < this->aux04)
            {
              aux06 = this->j - 1;
              t = this->number[this->aux06];
              number[this->aux06]=this->number[this->j];
              number[this->j]=this->t;
            }

          else
            nt = 0;

          j = this->j+1;
        }
      }
      i = this->i - 1;
    }
  }
  return 0;
}
int BBS_Print(struct BBS * this)
{
  int j;

  j = 0;
  while(this->j < this->size)
  {
    {
      System_out_println (this->number[this->j]);
      j = this->j+1;
    }
  }
  return 0;
}
int BBS_Init(struct BBS * this, int sz)
{

  size = this->sz;
  number = int* null=(int*)malloc(this->sz*sizeof(int));
  number[0]=20;
  number[1]=7;
  number[2]=12;
  number[3]=18;
  number[4]=2;
  number[5]=11;
  number[6]=6;
  number[7]=9;
  number[8]=19;
  number[9]=5;
  return 0;
}

// vtables
struct BubbleSort_vtable BubbleSort_vtable_ = 
{
};

struct BBS_vtable BBS_vtable_ = 
{
  BBS_Start,
  BBS_Sort,
  BBS_Print,
  BBS_Init,
};


// main method
int main ()
{
  struct BBS * x_0;
  System_out_println ((x_0=((struct BBS*)(Tiger_new (&BBS_vtable_, sizeof(struct BBS)))), x_0->vptr->Start(x_0, 10)));
}




